language: ruby

# for parallelizing tests across VMS, see https://docs.travis-ci.com/user/speeding-up-the-build/
env:
  - TRAVIS_TEST_SUITE=js
  - TRAVIS_TEST_SUITE=ruby

cache:
  directories:
  - $HOME/.cache/yarn # yarn
  - node_modules # yarn

rvm:
  - ruby-2.5.3

sudo: required

services:
  - postgres

branches:
  only:
    - master

before_install:
  - if [[ $TRAVIS_TEST_SUITE == "js" ]]; then export TZ=UTC; fi
  # see https://github.com/travis-ci/travis-ci/issues/7471#issuecomment-288832948
  - if [[ $TRAVIS_TEST_SUITE == "js" ]]; then curl -o- -L https://yarnpkg.com/install.sh | bash; fi
  - if [[ $TRAVIS_TEST_SUITE == "js" ]]; then export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"; fi
  # libsodium binary, from Heroku-14 stack (https://github.com/heroku/stack-images/blob/master/cedar-14/bin/cedar-14.sh#L7)
  # Even though we run Heroku-18 in production, our Travis setup is still running Ubuntu 14
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then echo "deb http://archive.ubuntu.com/ubuntu/ trusty main universe" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then echo "deb http://archive.ubuntu.com/ubuntu/ trusty-security main universe" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then echo "deb http://archive.ubuntu.com/ubuntu/ trusty-updates main universe" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then sudo apt-get update; fi
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then sudo apt-get install -y libsodium23; fi

install:
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then bundle install --retry=3; fi
  - if [[ $TRAVIS_TEST_SUITE == "js" ]]; then . $HOME/.nvm/nvm.sh; fi
  - if [[ $TRAVIS_TEST_SUITE == "js" ]]; then nvm install --lts; fi
  - if [[ $TRAVIS_TEST_SUITE == "js" ]]; then nvm use --lts; fi
  - if [[ $TRAVIS_TEST_SUITE == "js" ]]; then yarn install; fi

script:
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then bundle exec ruby-audit check; fi
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then bundle audit check --update; fi
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then bundle exec rake db:create db:migrate DATABASE_URL=postgres://localhost/student_insights_test; fi
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then bundle exec rake immigrant:check_keys; fi
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then rubocop; fi
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then bundle exec brakeman -z; fi
  - if [[ $TRAVIS_TEST_SUITE == "ruby" ]]; then ENABLE_RSPEC_COVERAGE_CHECKER=true bundle exec rspec spec; fi
  - if [[ $TRAVIS_TEST_SUITE == "js" ]]; then ./scripts/ci/detect_package_lock.sh; fi
  - if [[ $TRAVIS_TEST_SUITE == "js" ]]; then yarn test-cli; fi
