star_filenames:
  FILENAME_FOR_STAR_READING_IMPORT:                 SR_v2.csv
  FILENAME_FOR_STAR_MATH_IMPORT:                    SM_v2.csv
  FILENAME_FOR_STAR_ZIP_FILE:                       Somerville Public Schools.zip

# See FeedFilter::CommunitySchoolFilter
# Manual through console
community_schools_educators_sheet:
  https://docs.google.com/spreadsheets/d/1Xw33bKWJZ-rikGizO5CDfjMUeWJ0Rd23dWgN0xtHTxI/edit

# See StudentVoiceSurveyUploadsPage.js
# Semi-automated through web
student_voice_survey_form:
  https://docs.google.com/forms/d/180P2BFHK4TBgFC_7PLCW_AynhJP6ktBeKTJEQeTT44U/edit

# See StudentMeetingImporter.rb
# Semi-automated through console
student_meeting_sheet:
  https://docs.google.com/spreadsheets/d/1eMTJD8w-9R2NXtcYfiPRydQR-HDiH5fIydi1PA7-CU8/edit


school_definitions_for_import:
  - local_id: BRN
    slug: brn
    name: Benjamin G Brown
    school_type: ES

  - local_id: HEA
    slug: hea
    name: Arthur D Healey
    school_type: ESMS

  - local_id: KDY
    slug: kdy
    name: John F Kennedy
    school_type: ESMS

  - local_id: AFAS
    slug: afas
    name: Albert F. Argenziano School
    school_type: ESMS

  - local_id: ESCS
    slug: escs
    name: E Somerville Community
    school_type: ESMS

  - local_id: WSNS
    slug: wsns
    name: West Somerville Neighborhood
    school_type: ESMS

  - local_id: WHCS
    slug: whcs
    name: Winter Hill Community
    school_type: ESMS

  - local_id: NW
    slug: nw
    name: Next Wave Junior High
    school_type: MS

  - local_id: SHS
    slug: shs
    name: Somerville High
    school_type: HS

  - local_id: FC
    slug: fc
    name: Full Circle High School
    school_type: HS

  - local_id: CAP
    slug: cap
    name: Capuano Early Childhood Center
    school_type: ECS

  - local_id: PIC
    slug: pic
    name: Parent Information Center
    school_type: OTHER

  - local_id: SPED
    slug: sped
    name: SPED Outplacement and Walk-in
    school_type: OTHER


school_definitions_not_yet_used:
  - local_id: CUM
    slug: CUM
    name: Cummings School
    school_type: OTHER

  - local_id: PHCS
    slug: PHCS
    name: Powerhouse Community School
    school_type: OTHER

  - local_id: SCALE
    slug: SCALE
    name: Somerville Center for Adult Learning Experiences
    school_type: OTHER

  - local_id: HIST
    slug: HIST
    name: (Historical, marker for students who have graduated, withdrawn, etc.)
    school_type: OTHER
