# These are enabled by default, but were only noise when trying out this
# tool the first time, so we've disabled them.
# AlwaysAddDbIndexCheck: { }
# IsolateSeedDataCheck: { }
# LawOfDemeterCheck: { }
# MoveModelLogicIntoModelCheck: { use_count: 4 }
# OveruseRouteCustomizationsCheck: { customize_count: 3 }
# RemoveTrailingWhitespaceCheck: { }
# ReplaceInstanceVariableWithLocalVariableCheck: { }
# UseQueryAttributeCheck: { }

# These are disabled by default, but are valuable.
CheckSaveReturnValueCheck: { }
CheckDestroyReturnValueCheck: { }

# This is the biggest value in this tool:
RemoveUnusedMethodsInControllersCheck: { except_methods: [] }
RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
RemoveUnusedMethodsInModelsCheck: { except_methods: [] }



# Below are the defaults
AddModelVirtualAttributeCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: { }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
#RemoveTabCheck: { }
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
