# These are enabled by default, but were only noise when trying out this
# tool the first time, so we've disabled them.
# AlwaysAddDbIndexCheck: { }
# IsolateSeedDataCheck: { }
# LawOfDemeterCheck: { }
# MoveModelLogicIntoModelCheck: { use_count: 4 }
# OveruseRouteCustomizationsCheck: { customize_count: 3 }
# RemoveTrailingWhitespaceCheck: { }
# ReplaceInstanceVariableWithLocalVariableCheck: { }
# UseQueryAttributeCheck: { }

# These are disabled by default, but are valuable.
CheckSaveReturnValueCheck: { }
CheckDestroyReturnValueCheck: { }

# This is the biggest value in this tool so far, and found several bits
# of dead code on first run.  There's some false positives, and some places
# where
RemoveUnusedMethodsInHelpersCheck: { except_methods: [] }
RemoveUnusedMethodsInControllersCheck: {
  except_methods: [
    # False positives (often from metaprogramming, or implicit dependencies)
    'ApplicationController#after_sign_in_path_for',
    'ApplicationController#rollbar_anonymized_person_method',
    'Admin::EducatorsController#resource_params'
  ]
}
RemoveUnusedMethodsInModelsCheck: {
  except_methods: [
    # These are false positives (often from symbols passed to #as_json).
    'AnonymizedPersonForRollbar#initialize',
    'AnonymizedPersonForRollbar#rollbar_person_anonymized_identifier',
    'Student#latest_dibels',
    'Student#latest_access_results',
    'Student#winter_reading_doc',
    'TeamMembership#season_sort_key',

    # These are actually unused methods, but we want to keep them
    # sometimes this is to allow for manual use on the console, or to express
    # some kind of intent.
    'ClassListSnapshot#diffs_across_workspaces',
    'EdPlan#specific_disability',
    'EdPlan#persons_responsible',
    'EventNoteType#NGE',
    'EventNoteType#SST',
    'EventNoteType#TENGE',
    'EventNoteType#NEST',
    'SecondTransitionNote#has_restricted_text',
    'Service#never_discontinued',
    'Service#future_discontinue',
    'StudentVoiceCompletedSurvey#columns_for_form_v1_deprecated',
    'UnsafeAnonymizer#student_for_absence_dashboard',
    'UnsafeAnonymizer#star_student_assessment',
    'UnsafeAnonymizer#all_service_types'
  ]
}



# Below are the defaults
AddModelVirtualAttributeCheck: { }
DefaultScopeIsEvilCheck: { }
DryBundlerInCapistranoCheck: { }
#HashSyntaxCheck: { }
KeepFindersOnTheirOwnModelCheck: { }
#LongLineCheck: { max_line_length: 80 }
MoveCodeIntoControllerCheck: { }
MoveCodeIntoHelperCheck: { array_count: 3 }
MoveCodeIntoModelCheck: { use_count: 2 }
MoveFinderToNamedScopeCheck: { }
NeedlessDeepNestingCheck: { nested_count: 2 }
NotRescueExceptionCheck: { }
NotUseDefaultRouteCheck: { }
NotUseTimeAgoInWordsCheck: { }
ProtectMassAssignmentCheck: { }
RemoveEmptyHelpersCheck: { }
#RemoveTabCheck: { }
ReplaceComplexCreationWithFactoryMethodCheck: { attribute_assignment_count: 2 }
RestrictAutoGeneratedRoutesCheck: { }
SimplifyRenderInControllersCheck: { }
SimplifyRenderInViewsCheck: { }
#UseBeforeFilterCheck: { customize_count: 2 }
UseModelAssociationCheck: { }
UseMultipartAlternativeAsContentTypeOfEmailCheck: { }
#UseParenthesesInMethodDefCheck: { }
UseObserverCheck: { }
UseSayWithTimeInMigrationsCheck: { }
UseScopeAccessCheck: { }
UseTurboSprocketsRails3Check: { }
